# Generated by Django 2.2.24 on 2023-03-29 18:40

from django.db import migrations

def fill_own_property(apps, shcema_epitor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for owner in Owner.objects.all().iterator():
        flats = Flat.objects.filter(owner_name=owner.owner_name)
        owner.own_property.set(flats)




class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20230329_2126'),
    ]

    operations = [
        migrations.RunPython(fill_own_property)
    ]
