# Generated by Django 2.2.24 on 2023-03-30 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_auto_20230330_1311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='owner_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='own_property',
            new_name='property',
        ),
    ]
